### ISSUE TITLE
Svista in Ereditarietà PO1

### ISSUE THREAD

**Issue by Gabritorre** [M3nny/comp-sci#1]
Mentre copiavo questa tua bellissima tabella ho notato una piccola svista, Abstract field dovrebbe essere ❌

https://github.com/M3nny/comp-sci/blob/c8e569390bbd7c18fa9a88941c325657365a1577/Secondo%20anno/Programmazione%20ad%20oggetti%20mod.%201/Ereditariet%C3%A0.md?plain=1#L82C1-L88C1

**Comment by M3nny** [comment]
Hi Gabritorre,
thanks for reporting this issue, i've just pushed the fix.
